eureka:
  client:
    register-with-eureka: false
zuul:
  routes:
    books:
      strip-prefix: false
      path: /books/**
      serviceId: books
    authors:
      strip-prefix: false
      path: /authors/**
      serviceId: authors
ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000