spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost/ms_books?createDatabaseIfNotExist=true&useSSL=false
  application:
    name: books
  cloud:
    stream:
      bindings:
        authors:
          content-type: application/json
  rabbitmq:
    password: guest
    username: guest
    port: 5672
    host: localhost

server:
  port: 0