
spring:
  application:
    name: configuration-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fwfurtado/fj36-ms-configurations.git

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
server:
  port: 8090